# Generated by Django 3.0.3 on 2020-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailv', models.EmailField(max_length=30)),
                ('namev', models.CharField(max_length=30)),
                ('textv', models.TextField()),
            ],
        ),
    ]
