# Generated by Django 3.0.3 on 2020-03-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactt',
            old_name='emailv',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactt',
            old_name='namev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactt',
            old_name='textv',
            new_name='text',
        ),
    ]
